version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "daily"
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "4.0"
    - "4.0.rc2"
