//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.3705.0.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="QuerySoapBinding", Namespace="urn:exist")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(QueryResponseDocument))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(QueryResponseCollection))]
public class QueryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public QueryService() {
        this.Url = "http://localhost:8080/exist/services/Query";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:exist", ResponseNamespace="urn:exist")]
    [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="base64Binary")]
    public System.Byte[] getResource(string in0, string in1, bool in2) {
        object[] results = this.Invoke("getResource", new object[] {
                    in0,
                    in1,
                    in2});
        return ((System.Byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetResource(string in0, string in1, bool in2, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getResource", new object[] {
                    in0,
                    in1,
                    in2}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Byte[] EndgetResource(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Byte[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:exist", ResponseNamespace="urn:exist")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public QueryResponse query(string in0) {
        object[] results = this.Invoke("query", new object[] {
                    in0});
        return ((QueryResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginquery(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("query", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public QueryResponse Endquery(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((QueryResponse)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:exist", ResponseNamespace="urn:exist")]
    [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="base64Binary")]
    public System.Byte[] retrieve(int in0, int in1, string in2, bool in3) {
        object[] results = this.Invoke("retrieve", new object[] {
                    in0,
                    in1,
                    in2,
                    in3});
        return ((System.Byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginretrieve(int in0, int in1, string in2, bool in3, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("retrieve", new object[] {
                    in0,
                    in1,
                    in2,
                    in3}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Byte[] Endretrieve(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Byte[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:exist", ResponseNamespace="urn:exist")]
    [return: System.Xml.Serialization.SoapElementAttribute("return", DataType="base64Binary")]
    public System.Byte[] retrieveByDocument(int in0, int in1, string in2, string in3, bool in4) {
        object[] results = this.Invoke("retrieveByDocument", new object[] {
                    in0,
                    in1,
                    in2,
                    in3,
                    in4});
        return ((System.Byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginretrieveByDocument(int in0, int in1, string in2, string in3, bool in4, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("retrieveByDocument", new object[] {
                    in0,
                    in1,
                    in2,
                    in3,
                    in4}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Byte[] EndretrieveByDocument(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Byte[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:exist", ResponseNamespace="urn:exist")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public Collection listCollection(string in0) {
        object[] results = this.Invoke("listCollection", new object[] {
                    in0});
        return ((Collection)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginlistCollection(string in0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("listCollection", new object[] {
                    in0}, callback, asyncState);
    }
    
    /// <remarks/>
    public Collection EndlistCollection(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Collection)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("QueryResponse", "urn:exist")]
public class QueryResponse {
    
    /// <remarks/>
    public int hits;
    
    /// <remarks/>
    public int resultSetId;
    
    /// <remarks/>
    public long queryTime;
    
    /// <remarks/>
    public QueryResponseCollection[] collections;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("QueryResponseCollection", "urn:exist")]
public class QueryResponseCollection {
    
    /// <remarks/>
    public string collectionName;
    
    /// <remarks/>
    public QueryResponseDocument[] documents;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("QueryResponseDocument", "urn:exist")]
public class QueryResponseDocument {
    
    /// <remarks/>
    public string documentName;
    
    /// <remarks/>
    public int hitCount;
}

/// <remarks/>
[System.Xml.Serialization.SoapTypeAttribute("Collection", "urn:exist")]
public class Collection {
    
    /// <remarks/>
    public string[] collections;
    
    /// <remarks/>
    public string[] resources;
}
