xquery version "1.0";

declare option exist:serialize "method=xhtml media-type=text/html indent=no";

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xf="http://www.w3.org/2002/xforms">
    <head>
        <title>Hello World in XForms</title>
        <xf:model>
            <xf:instance>
                <request xmlns="">
                    <host>{request:get-server-name()}</host>
                    <remote-host>{request:get-remote-host()}</remote-host>
                    <remote-ip>{request:get-remote-addr()}</remote-ip>
                </request>
            </xf:instance>
            <xf:instance id="emails">
                <emails xmlns="">
                    <email/>
                </emails>
            </xf:instance>
        </xf:model>
    </head>
    <body>
        <h1>Dynamic XForms generated by XQuery:</h1>

        <p>Request info:</p>
        
        <ul>
            <li>
                <xf:output value="host">
                    <xf:label>Server hostname: </xf:label>
                </xf:output>
            </li>
            <li>
                <xf:output value="remote-host">
                    <xf:label>Your hostname: </xf:label>
                </xf:output>
            </li>
            <li>
                <xf:output value="remote-ip">
                    <xf:label>Your IP: </xf:label>
                </xf:output>
            </li>
        </ul>
        
        <p>
            <xf:input ref="instance('emails')/email" incremental="true">
                <xf:label>Enter your email: </xf:label>
            </xf:input>
        </p>
        <p>
            <xf:output value="instance('emails')/email">
                <xf:label>Entered email: </xf:label>
            </xf:output>
        </p>
    </body>
</html>