;; $Id$
(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-project-name "eXist Free Software Native XML Database")
 '(jde-run-working-directory ".")
 '(jde-javadoc-describe-interface-template "\"* The interface \" (jde-javadoc-code name) ")
 '(jde-javadoc-describe-method-template "\"* The method \" (jde-javadoc-code name) ")
 '(jde-javadoc-author-tag-template "\"* @author \" user-full-name \" <\" user-mail-address \"> \"")
 '(jde-javadoc-describe-field-template "\"* The templates \" (jde-javadoc-field-type modifiers)
 \" \" (jde-javadoc-code name) ")
 '(jde-sourcepath (quote ("./src" "./test/src" "./tools/XFormsFilter/src" "./tools/ircbot/src" "./tools/izpack/src" "./tools/requestlog/src" "./tools/wrapper/src" "./samples/src" "./thirdparty/jboss/src" "./extensions/xprocxq/main/src" "./extensions/modules/src" "./extensions/fluent/src" "./extensions/fluent/test/src" "./extensions/indexes/ngram/src" "./extensions/indexes/ngram/test/src" "./extensions/indexes/spatial/src" "./extensions/indexes/spatial/test/src" "./extensions/indexes/lucene/src" "./extensions/indexes/lucene/test/src" "./extensions/versioning/src")))
 '(jde-run-application-class "org.exist.start.Main.class")
 '(jde-built-class-path (quote ("./build/classes" "./test/classes" "./tools/wrapper/classes" "./webapps/exist/WEB-INF/classes" "./extensions/modules/classes" "./extensions/fluent/test/classes" "./extensions/fluent/classes" "./extensions/indexes/ngram/test/classes" "./extensions/indexes/ngram/classes" "./extensions/indexes/spatial/test/classes" "./extensions/indexes/spatial/classes" "./extensions/indexes/lucene/test/classes" "./extensions/indexes/lucene/classes" "./extensions/versioning/classes" "./tools/requestlog/classes" "./tools/ircbot/classes")))
 '(jde-xref-store-prefixes (quote ("org.exist" "org.apache" "org.xmldb")))
 '(jde-javadoc-describe-class-template "\"* The class \" (jde-javadoc-code name) ")
 '(jde-db-option-connect-socket (quote ("localhost" "4444")))
 '(jde-enable-abbrev-mode t)
 '(jde-findbugs-directory "~/bin/findbugs-1.1.1")
 '(jde-jdk-registry (quote (("1.6.0" . "/opt/java/"))))
 '(jswat-path "~/bin/jswat-3.16")
)
