/*
 * eXist-db Open Source Native XML Database
 * Copyright (C) 2001 The eXist-db Authors
 *
 * info@exist-db.org
 * http://www.exist-db.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package org.exist.client.security;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.Serial;
import java.util.Arrays;
import java.util.Iterator;
import java.util.regex.Pattern;
import javax.swing.GroupLayout;
import javax.swing.InputVerifier;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import org.exist.client.InteractiveClient;
import org.exist.security.AXSchemaType;
import org.exist.security.EXistSchemaType;
import org.exist.security.Permission;
import org.exist.security.PermissionDeniedException;
import org.exist.security.internal.aider.GroupAider;
import org.exist.security.internal.aider.UserAider;
import org.exist.xmldb.UserManagementService;
import org.xmldb.api.base.XMLDBException;

/**
 * @author <a href="mailto:adam.retter@googlemail.com">Adam Retter</a>
 */
public class UserDialog extends JFrame {
    @Serial
    private static final long serialVersionUID = -7544980948396443454L;
    private static final Pattern PTN_USERNAME = Pattern.compile("[a-zA-Z0-9\\-._@]{3,}");
    private static final Pattern PTN_PASSWORD = Pattern.compile(".{3,}");
    private static final String CREATE_USER_ERROR = "Create User Error";

    protected JSpinner spnUmask;
    protected JTextField txtDescription;
    protected JTextField txtFullName;
    protected JPasswordField txtPassword;
    protected JPasswordField txtPasswordConfirm;
    protected JTextField txtUsername;
    protected JButton btnCreate;
    protected JCheckBox cbDisabled;
    protected JCheckBox cbPersonalGroup;

    private UserManagementService userManagementService;
    private SortedListModel<String> availableGroupsModel;
    private SortedListModel<String> memberOfGroupsModel;
    private String primaryGroup;
    private JCheckBoxMenuItem cbmiPrimaryGroup;
    private JList<String> lstAvailableGroups;
    private JList<String> lstMemberOfGroups;
    private MemberOfGroupsListCellRenderer memberOfGroupsListCellRenderer;

    public UserDialog(final UserManagementService userManagementService) {
        this.userManagementService = userManagementService;
        InteractiveClient.setExistImage(getClass(), this::setIconImage);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        JPopupMenu pmMemberOfGroups = new JPopupMenu();
        cbmiPrimaryGroup = new JCheckBoxMenuItem();
        JSeparator jSeparator1 = new JSeparator();
        JLabel lblUsername = new JLabel();
        txtUsername = new JTextField();
        JLabel lblFullName = new JLabel();
        txtFullName = new JTextField();
        JLabel lblDescription = new JLabel();
        txtDescription = new JTextField();
        JLabel lblPassword = new JLabel();
        txtPassword = new JPasswordField();
        JLabel lblPasswordConfirm = new JLabel();
        txtPasswordConfirm = new JPasswordField();
        cbDisabled = new JCheckBox();
        JSeparator jSeparator2 = new JSeparator();
        spnUmask = new JSpinner();
        JLabel lblUmask = new JLabel();
        JSeparator jSeparator3 = new JSeparator();
        JButton btnClose = new JButton();
        btnCreate = new JButton();
        cbPersonalGroup = new JCheckBox();
        JScrollPane jScrollPane1 = new JScrollPane();
        lstMemberOfGroups = new JList<>();
        JLabel lblMemberOfGroups = new JLabel();
        JScrollPane jScrollPane2 = new JScrollPane();
        lstAvailableGroups = new JList<>();
        JLabel lblAvailableGroups = new JLabel();
        JButton btnAddGroup = new JButton();
        JButton btnRemoveGroup = new JButton();
        JSeparator jSeparator4 = new JSeparator();

        cbmiPrimaryGroup.setSelected(true);
        cbmiPrimaryGroup.setText("Primary Group");
        cbmiPrimaryGroup.addActionListener(a -> cbmiPrimaryGroupActionPerformed());
        pmMemberOfGroups.add(cbmiPrimaryGroup);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New User");

        lblUsername.setText("User name:");
        txtUsername.setInputVerifier(getUsernameInputVerifier());
        lblFullName.setText("Full name:");
        lblDescription.setText("Description:");
        lblPassword.setText("Password:");
        txtPassword.setInputVerifier(getPasswordInputVerifier());
        lblPasswordConfirm.setText("Confirm password:");
        txtPasswordConfirm.setInputVerifier(getPasswordInputVerifier());
        cbDisabled.setText("Account is disabled");

        spnUmask.setModel(new UmaskSpinnerModel());
        spnUmask.setEditor(new UmaskEditor(spnUmask));
        spnUmask.setValue(getUmask());

        lblUmask.setText("umask:");

        btnClose.setText("Close");
        btnClose.addActionListener(a -> btnCloseActionPerformed());

        btnCreate.setText("Create");
        btnCreate.addActionListener(a -> btnCreateActionPerformed());

        cbPersonalGroup.setSelected(true);
        cbPersonalGroup.setText("Create personal user group");

        lstMemberOfGroups.setModel(getMemberOfGroupsListModel());
        lstMemberOfGroups.setCellRenderer(getMemberOfGroupsListCellRenderer());
        lstMemberOfGroups.setComponentPopupMenu(pmMemberOfGroups);
        lstMemberOfGroups.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                lstMemberOfGroupsMouseClicked();
            }
        });
        jScrollPane1.setViewportView(lstMemberOfGroups);

        lblMemberOfGroups.setText("Member of Groups:");

        lstAvailableGroups.setModel(getAvailableGroupsListModel());
        jScrollPane2.setViewportView(lstAvailableGroups);

        lblAvailableGroups.setText("Available Groups:");

        btnAddGroup.setText("->");
        btnAddGroup.setToolTipText("Add to Group");
        btnAddGroup.addActionListener(a -> btnAddGroupActionPerformed());

        btnRemoveGroup.setText("<-");
        btnRemoveGroup.setToolTipText("Remove from Group");
        btnRemoveGroup.addActionListener(a -> btnRemoveGroupActionPerformed());

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnClose)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnCreate)
                                                                .addGap(6, 6, 6))
                                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(btnAddGroup, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(btnRemoveGroup, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                                                        .addComponent(lblAvailableGroups))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblMemberOfGroups)
                                                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(25, 25, 25)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                        .addComponent(lblDescription)
                                                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(lblFullName)
                                                                                        .addGap(24, 24, 24)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(lblUsername)
                                                                                .addGap(3, 3, 3)))
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(txtUsername, GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                                                        .addComponent(txtFullName, GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtDescription, GroupLayout.Alignment.LEADING)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblPasswordConfirm)
                                                                        .addComponent(lblPassword))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(txtPassword, GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                                                        .addComponent(txtPasswordConfirm))))
                                                .addGap(0, 35, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator4)
                                                        .addComponent(jSeparator1, GroupLayout.Alignment.LEADING))))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(lblUmask)
                                                .addGap(18, 18, 18)
                                                .addComponent(spnUmask, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator2)
                                                        .addComponent(jSeparator3))
                                                .addContainerGap())))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(cbDisabled))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(cbPersonalGroup)))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblUsername)
                                        .addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFullName)
                                        .addComponent(txtFullName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDescription)
                                        .addComponent(txtDescription, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPassword)
                                        .addComponent(txtPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPasswordConfirm, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPasswordConfirm))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDisabled)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(spnUmask, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUmask))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPersonalGroup)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMemberOfGroups, GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAvailableGroups))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(btnAddGroup)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnRemoveGroup)))
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(btnClose)
                                        .addComponent(btnCreate))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    private void btnCloseActionPerformed() {
        setVisible(false);
        dispose();
    }

    private void btnCreateActionPerformed() {
        if (!isValidUserDetails()) {
            return;
        }

        //create the user
        createUser();

        //close the dialog
        setVisible(false);
        dispose();
    }

    protected void createUser() {

        //0 - determine the primary group
        final GroupAider primaryGroupAider;
        if (getPrimaryGroup() == null) {
            if (cbPersonalGroup.isSelected()) {
                primaryGroupAider = new GroupAider(txtUsername.getText());
            } else {
                final String firstGroup = memberOfGroupsModel.firstElement();
                if (firstGroup != null) {
                    primaryGroupAider = new GroupAider(firstGroup);
                } else {
                    JOptionPane.showMessageDialog(this, "Could not determine primary group for user '" + txtUsername.getText() + "'. User must create personal group or belong to at least one existing group", CREATE_USER_ERROR, JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } else {
            primaryGroupAider = new GroupAider(getPrimaryGroup());
        }

        //1 - create personal group
        GroupAider groupAider = null;
        if (cbPersonalGroup.isSelected()) {
            groupAider = new GroupAider(txtUsername.getText());
            groupAider.setMetadataValue(EXistSchemaType.DESCRIPTION, "Personal group for " + txtUsername.getText());
            try {
                getUserManagementService().addGroup(groupAider);
            } catch (final XMLDBException xmldbe) {
                JOptionPane.showMessageDialog(this, "Could not create personal group '" + txtUsername.getText() + "': " + xmldbe.getMessage(), CREATE_USER_ERROR, JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        //2 - create the user
        final UserAider userAider = new UserAider(txtUsername.getText());
        userAider.setMetadataValue(AXSchemaType.FULLNAME, txtFullName.getText());
        userAider.setMetadataValue(EXistSchemaType.DESCRIPTION, txtDescription.getText());
        userAider.setPassword(String.valueOf(txtPassword.getPassword()));
        userAider.setEnabled(!cbDisabled.isSelected());
        userAider.setUserMask(UmaskSpinnerModel.octalUmaskToInt((String) spnUmask.getValue()));

        //add the personal group to the user
        if (cbPersonalGroup.isSelected()) {
            userAider.addGroup(txtUsername.getText());
        }

        //add any other groups to the user
        final Iterator<String> itMemberOfGroups = memberOfGroupsModel.iterator();
        while (itMemberOfGroups.hasNext()) {
            final String memberOfGroup = itMemberOfGroups.next();
            userAider.addGroup(memberOfGroup);
        }

        //set the primary group
        try {
            userAider.setPrimaryGroup(primaryGroupAider);
        } catch (final PermissionDeniedException pde) {
            JOptionPane.showMessageDialog(this, "Could not set primary group '" + getPrimaryGroup() + "' of user '" + txtUsername.getText() + "': " + pde.getMessage(), CREATE_USER_ERROR, JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            getUserManagementService().addAccount(userAider);
        } catch (final XMLDBException xmldbe) {
            JOptionPane.showMessageDialog(this, "Could not create user '" + txtUsername.getText() + "': " + xmldbe.getMessage(), CREATE_USER_ERROR, JOptionPane.ERROR_MESSAGE);
            return;
        }

        //3 - if created personal group, then add us as the manager
        if (cbPersonalGroup.isSelected() && groupAider != null) {
            try {
                groupAider.addManager(userAider);
                getUserManagementService().updateGroup(groupAider);
            } catch (final XMLDBException | PermissionDeniedException xmldbe) {
                JOptionPane.showMessageDialog(this, "Could not set user '" + txtUsername.getText() + "' as manager of personal group '" + txtUsername.getText() + "': " + xmldbe.getMessage(), CREATE_USER_ERROR, JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnAddGroupActionPerformed() {
        for (final String value : lstAvailableGroups.getSelectedValuesList()) {
            memberOfGroupsModel.add(value);
            availableGroupsModel.removeElement(value);

            //is this the first group added to the user?
            if (getMemberOfGroupsListModel().getSize() == 1 && !cbPersonalGroup.isSelected()) {
                final String firstGroup = getMemberOfGroupsListModel().getElementAt(0);
                setPrimaryGroup(firstGroup);
                getMemberOfGroupsListCellRenderer().setCellOfInterest(getPrimaryGroup());
            }
        }
    }

    private void btnRemoveGroupActionPerformed() {
        for (final String group : lstMemberOfGroups.getSelectedValuesList()) {
            availableGroupsModel.add(group);
            memberOfGroupsModel.removeElement(group);

            //are we removing the users primary group?
            if (group.equals(getPrimaryGroup())) {
                if (getMemberOfGroupsListModel().getSize() == 0 || cbPersonalGroup.isSelected()) {
                    setPrimaryGroup(null);
                } else {
                    //default to the first group
                    final String firstGroup = getMemberOfGroupsListModel().getElementAt(0);
                    setPrimaryGroup(firstGroup);
                }
            }
            getMemberOfGroupsListCellRenderer().setCellOfInterest(getPrimaryGroup());
        }
    }

    private void cbmiPrimaryGroupActionPerformed() {
        final String newPrimaryGroup = getMemberOfGroupsListModel().getElementAt(lstMemberOfGroups.getSelectedIndex());
        if (newPrimaryGroup.equals(this.primaryGroup)) {
            // deselect existing primary group
            this.primaryGroup = null;
        } else {
            // select new primary group
            this.primaryGroup = newPrimaryGroup;
        }
        getMemberOfGroupsListCellRenderer().setCellOfInterest(primaryGroup);
    }

    private void lstMemberOfGroupsMouseClicked() {
        cbmiPrimaryGroup.setState((getMemberOfGroupsListModel().getElementAt(lstMemberOfGroups.getSelectedIndex())).equals(primaryGroup));
    }

    private boolean isValidUserDetails() {
        return isValidUsername() && isValidPassword() && isValidGroups();
    }

    private boolean isValidUsername() {
        if (PTN_USERNAME.matcher(txtUsername.getText()).matches()) {
            return true;
        }

        JOptionPane.showMessageDialog(this, "Username must be at least 3 characters (" + PTN_USERNAME + ")");
        return false;
    }

    private boolean isValidPassword() {
        if (txtPassword != null) {
            final char[] password = txtPassword.getPassword();
            return PTN_PASSWORD.matcher(String.valueOf(password)).matches() && Arrays.equals(password, txtPasswordConfirm.getPassword());
        }

        JOptionPane.showMessageDialog(this, "Passwords do not match or are less than 3 characters.");
        return false;
    }

    private boolean isValidGroups() {
        if (cbPersonalGroup.isSelected() || memberOfGroupsModel.getSize() > 0) {
            return true;
        }

        JOptionPane.showMessageDialog(this, "The user must be in at least one group, or a personal group must be created for them.");
        return false;
    }

    private InputVerifier getUsernameInputVerifier() {
        return new RegExpInputVerifier(PTN_USERNAME);
    }

    private InputVerifier getPasswordInputVerifier() {
        return new RegExpInputVerifier(PTN_PASSWORD);
    }

    private String getUmask() {
        return "%4s".formatted(Integer.toString(Permission.DEFAULT_UMASK, UmaskSpinnerModel.OCTAL_RADIX)).replace(' ', '0');
    }

    protected SortedListModel<String> getAvailableGroupsListModel() {
        if (availableGroupsModel == null) {
            try {
                final String[] groupNames = getUserManagementService().getGroups();
                availableGroupsModel = new SortedListModel<>();
                availableGroupsModel.addAll(groupNames);
            } catch (final XMLDBException xmldbe) {
                JOptionPane.showMessageDialog(this, "Could not get available groups: " + xmldbe.getMessage(), CREATE_USER_ERROR, JOptionPane.ERROR_MESSAGE);
            }
        }
        return availableGroupsModel;
    }

    protected SortedListModel<String> getMemberOfGroupsListModel() {
        if (memberOfGroupsModel == null) {
            memberOfGroupsModel = new SortedListModel<>();
        }
        return memberOfGroupsModel;
    }

    protected UserManagementService getUserManagementService() {
        return userManagementService;
    }

    protected void setPrimaryGroup(final String primaryGroup) {
        this.primaryGroup = primaryGroup;
    }

    protected String getPrimaryGroup() {
        return primaryGroup;
    }

    protected void setUserManagementService(final UserManagementService userManagementService) {
        this.userManagementService = userManagementService;
    }

    protected MemberOfGroupsListCellRenderer getMemberOfGroupsListCellRenderer() {
        if (memberOfGroupsListCellRenderer == null) {
            memberOfGroupsListCellRenderer = new MemberOfGroupsListCellRenderer();
        }
        return memberOfGroupsListCellRenderer;
    }
}
