<?xml version="1.0" encoding="UTF-8"?>
<!--
    Generates org.exist.util.GeneratedSchemaVersions, one String constant per canonical XSD,
    read directly from each XSD's xs:schema/@version. Runs on every normal build (generate-sources
    phase, see exist-core/pom.xml's schema-version-codegen execution). Unlike
    schema/governance.xsl (phase=none, CI-invoked-only, which only catches drift on a diff
    touching both files at once), this means SchemaVersion.java's version constants can never
    silently drift from schema/*.xsd.

    The 5 canonical-XSD to Java-constant-name pairs are hand-maintained below (the same 5
    SchemaVersion.java itself names); adding a 6th canonical schema needs a matching edit here,
    same as it would need a new constant in SchemaVersion.java today. Only the *version value*
    itself is what this eliminates manual upkeep for.

    Resolves the 5 XSDs as siblings of this stylesheet's trigger input (see
    schema/GeneratedSchemaVersions.xml) via base-uri(), so no stylesheet parameter is needed.
-->
<xsl:stylesheet version="2.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xsl:output method="text" encoding="UTF-8"/>

    <xsl:variable name="pairs" as="element(pair)*">
        <pair name="CONF" file="conf.xsd"/>
        <pair name="COLLECTION_XCONF" file="collection.xconf.xsd"/>
        <pair name="DESCRIPTOR" file="descriptor.xsd"/>
        <pair name="CONTROLLER_CONFIG" file="controller-config.xsd"/>
        <pair name="MIME_TYPES" file="mime-types.xsd"/>
    </xsl:variable>

    <xsl:template match="/">
        <xsl:variable name="base" select="base-uri(/)"/>
        <xsl:text>/*
 * eXist-db Open Source Native XML Database
 * Copyright (C) 2001 The eXist-db Authors
 *
 * GENERATED by schema/generate-schema-version.xsl at build time -- do not edit by hand.
 * Source of truth: each canonical XSD's xs:schema/@version, under schema/.
 */
package org.exist.util;

/**
 * Build-time-generated {@code xs:schema/@version} values for the canonical native XSDs -- see
 * {@link SchemaVersion}, which exposes these under its own stable, hand-written constant names.
 */
final class GeneratedSchemaVersions {

    private GeneratedSchemaVersions() {
    }
</xsl:text>
        <xsl:for-each select="$pairs">
            <xsl:variable name="uri" select="resolve-uri(string(@file), $base)"/>
            <xsl:variable name="version" select="if (doc-available($uri))
                then document($uri)/xs:schema/@version else ()"/>
            <xsl:if test="empty($version)">
                <xsl:message terminate="yes">generate-schema-version.xsl: <xsl:value-of select="@file"/>
                    has no xs:schema/@version (resolved as <xsl:value-of select="$uri"/>) -- cannot generate <xsl:value-of select="@name"/>.</xsl:message>
            </xsl:if>
            <xsl:text>    static final String </xsl:text>
            <xsl:value-of select="@name"/>
            <xsl:text> = "</xsl:text>
            <xsl:value-of select="$version"/>
            <xsl:text>";
</xsl:text>
        </xsl:for-each>
        <xsl:text>}
</xsl:text>
    </xsl:template>

</xsl:stylesheet>
