// $ANTLR 2.7.2: "XPathParser2.g" -> "XPathParser2.java"$

	package org.exist.parser;

	import antlr.debug.misc.*;
	import java.io.StringReader;
	import java.io.BufferedReader;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Iterator;
	import java.util.Stack;
	import org.exist.storage.BrokerPool;
	import org.exist.storage.DBBroker;
	import org.exist.storage.analysis.Tokenizer;
	import org.exist.EXistException;
	import org.exist.dom.DocumentSet;
	import org.exist.dom.DocumentImpl;
	import org.exist.dom.QName;
	import org.exist.security.PermissionDeniedException;
	import org.exist.security.User;
	import org.exist.xpath.*;
	import org.exist.xpath.value.*;
	import org.exist.xpath.functions.*;

public interface XPathParser2TokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int QNAME = 4;
	int PREDICATE = 5;
	int FLWOR = 6;
	int PARENTHESIZED = 7;
	int ABSOLUTE_SLASH = 8;
	int ABSOLUTE_DSLASH = 9;
	int WILDCARD = 10;
	int PREFIX_WILDCARD = 11;
	int FUNCTION = 12;
	int UNARY_MINUS = 13;
	int UNARY_PLUS = 14;
	int XPOINTER = 15;
	int XPOINTER_ID = 16;
	int VARIABLE_REF = 17;
	int VARIABLE_BINDING = 18;
	int ELEMENT = 19;
	int ATTRIBUTE = 20;
	int TEXT = 21;
	int VERSION_DECL = 22;
	int NAMESPACE_DECL = 23;
	int DEF_NAMESPACE_DECL = 24;
	int DEF_FUNCTION_NS_DECL = 25;
	int GLOBAL_VAR = 26;
	int FUNCTION_DECL = 27;
	int PROLOG = 28;
	int ATOMIC_TYPE = 29;
	int MODULE = 30;
	int ORDER_BY = 31;
	int POSITIONAL_VAR = 32;
	int BEFORE = 33;
	int AFTER = 34;
	int LITERAL_xpointer = 35;
	int LPAREN = 36;
	int RPAREN = 37;
	int NCNAME = 38;
	int XQUERY = 39;
	int VERSION = 40;
	int SEMICOLON = 41;
	int LITERAL_declare = 42;
	int LITERAL_namespace = 43;
	int LITERAL_default = 44;
	int LITERAL_function = 45;
	int LITERAL_variable = 46;
	int STRING_LITERAL = 47;
	int EQ = 48;
	int LITERAL_element = 49;
	int DOLLAR = 50;
	int LCURLY = 51;
	int RCURLY = 52;
	int LITERAL_as = 53;
	int COMMA = 54;
	int LITERAL_empty = 55;
	int QUESTION = 56;
	int STAR = 57;
	int PLUS = 58;
	int LITERAL_item = 59;
	int LITERAL_for = 60;
	int LITERAL_let = 61;
	int LITERAL_some = 62;
	int LITERAL_every = 63;
	int LITERAL_if = 64;
	int LITERAL_where = 65;
	int LITERAL_return = 66;
	int LITERAL_in = 67;
	int LITERAL_at = 68;
	int COLON = 69;
	int LITERAL_order = 70;
	int LITERAL_by = 71;
	int LITERAL_ascending = 72;
	int LITERAL_descending = 73;
	int LITERAL_greatest = 74;
	int LITERAL_least = 75;
	int LITERAL_satisfies = 76;
	int LITERAL_then = 77;
	int LITERAL_else = 78;
	int LITERAL_or = 79;
	int LITERAL_and = 80;
	int LITERAL_cast = 81;
	int LT = 82;
	int GT = 83;
	int LITERAL_eq = 84;
	int LITERAL_ne = 85;
	int LITERAL_lt = 86;
	int LITERAL_le = 87;
	int LITERAL_gt = 88;
	int LITERAL_ge = 89;
	int NEQ = 90;
	int GTEQ = 91;
	int LTEQ = 92;
	int LITERAL_is = 93;
	int LITERAL_isnot = 94;
	int ANDEQ = 95;
	int OREQ = 96;
	int LITERAL_to = 97;
	int MINUS = 98;
	int LITERAL_div = 99;
	int LITERAL_idiv = 100;
	int LITERAL_mod = 101;
	int LITERAL_union = 102;
	int UNION = 103;
	int LITERAL_intersect = 104;
	int LITERAL_except = 105;
	int SLASH = 106;
	int DSLASH = 107;
	int LITERAL_text = 108;
	int LITERAL_node = 109;
	int SELF = 110;
	int XML_COMMENT = 111;
	int LPPAREN = 112;
	int RPPAREN = 113;
	int AT = 114;
	int PARENT = 115;
	int LITERAL_child = 116;
	int LITERAL_self = 117;
	int LITERAL_attribute = 118;
	int LITERAL_descendant = 119;
	// "descendant-or-self" = 120
	// "following-sibling" = 121
	int LITERAL_parent = 122;
	int LITERAL_ancestor = 123;
	// "ancestor-or-self" = 124
	// "preceding-sibling" = 125
	int DOUBLE_LITERAL = 126;
	int DECIMAL_LITERAL = 127;
	int INTEGER_LITERAL = 128;
	int LITERAL_comment = 129;
	// "processing-instruction" = 130
	// "document-node" = 131
	int WS = 132;
	int END_TAG_START = 133;
	int QUOT = 134;
	int ATTRIBUTE_CONTENT = 135;
	int ELEMENT_CONTENT = 136;
	int XML_COMMENT_END = 137;
	int XML_PI = 138;
	int XML_PI_END = 139;
	int LITERAL_document = 140;
	int LITERAL_collection = 141;
	int XML_PI_START = 142;
	int LETTER = 143;
	int DIGITS = 144;
	int HEX_DIGITS = 145;
	int NMSTART = 146;
	int NMCHAR = 147;
	int EXPR_COMMENT = 148;
	int PREDEFINED_ENTITY_REF = 149;
	int CHAR_REF = 150;
	int NEXT_TOKEN = 151;
	int CHAR = 152;
	int BASECHAR = 153;
	int IDEOGRAPHIC = 154;
	int COMBINING_CHAR = 155;
	int DIGIT = 156;
	int EXTENDER = 157;
}
