// $ANTLR 2.7.2: "XPathParser2.g" -> "XPathParser2.java"$

	package org.exist.parser;

	import antlr.debug.misc.*;
	import java.io.StringReader;
	import java.io.BufferedReader;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Iterator;
	import org.exist.storage.BrokerPool;
	import org.exist.storage.DBBroker;
	import org.exist.storage.analysis.Tokenizer;
	import org.exist.EXistException;
	import org.exist.dom.DocumentSet;
	import org.exist.dom.DocumentImpl;
	import org.exist.dom.QName;
	import org.exist.security.PermissionDeniedException;
	import org.exist.security.User;
	import org.exist.xpath.*;
	import org.exist.xpath.value.*;
	import org.exist.xpath.functions.*;

public interface XPathParser2TokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int QNAME = 4;
	int PREDICATE = 5;
	int FLWOR = 6;
	int PARENTHESIZED = 7;
	int ABSOLUTE_SLASH = 8;
	int ABSOLUTE_DSLASH = 9;
	int WILDCARD = 10;
	int PREFIX_WILDCARD = 11;
	int FUNCTION = 12;
	int UNARY_MINUS = 13;
	int UNARY_PLUS = 14;
	int XPOINTER = 15;
	int XPOINTER_ID = 16;
	int VARIABLE_REF = 17;
	int VARIABLE_BINDING = 18;
	int ELEMENT = 19;
	int ATTRIBUTE = 20;
	int TEXT = 21;
	int VERSION_DECL = 22;
	int NAMESPACE_DECL = 23;
	int DEF_NAMESPACE_DECL = 24;
	int GLOBAL_VAR = 25;
	int LITERAL_xpointer = 26;
	int LPAREN = 27;
	int RPAREN = 28;
	int NCNAME = 29;
	int SEMICOLON = 30;
	int LITERAL_declare = 31;
	int LITERAL_namespace = 32;
	int LITERAL_default = 33;
	int LITERAL_xquery = 34;
	int LITERAL_version = 35;
	int STRING_LITERAL = 36;
	int EQ = 37;
	int LITERAL_element = 38;
	int LITERAL_variable = 39;
	int DOLLAR = 40;
	int LCURLY = 41;
	int RCURLY = 42;
	int COMMA = 43;
	int LITERAL_where = 44;
	int LITERAL_return = 45;
	int LITERAL_for = 46;
	int LITERAL_let = 47;
	int LITERAL_in = 48;
	int COLON = 49;
	int LITERAL_or = 50;
	int LITERAL_and = 51;
	int NEQ = 52;
	int GT = 53;
	int GTEQ = 54;
	int LT = 55;
	int LTEQ = 56;
	int ANDEQ = 57;
	int OREQ = 58;
	int LITERAL_to = 59;
	int PLUS = 60;
	int MINUS = 61;
	int STAR = 62;
	int LITERAL_div = 63;
	int LITERAL_mod = 64;
	int UNION = 65;
	int SLASH = 66;
	int DSLASH = 67;
	int LITERAL_text = 68;
	int LITERAL_node = 69;
	int SELF = 70;
	int XML_COMMENT = 71;
	int LPPAREN = 72;
	int RPPAREN = 73;
	int AT = 74;
	int PARENT = 75;
	int LITERAL_child = 76;
	int LITERAL_self = 77;
	int LITERAL_attribute = 78;
	int LITERAL_descendant = 79;
	// "descendant-or-self" = 80
	// "following-sibling" = 81
	int LITERAL_parent = 82;
	int LITERAL_ancestor = 83;
	// "ancestor-or-self" = 84
	// "preceding-sibling" = 85
	int DOUBLE_LITERAL = 86;
	int DECIMAL_LITERAL = 87;
	int INTEGER_LITERAL = 88;
	int WS = 89;
	int END_TAG_START = 90;
	int QUOT = 91;
	int ATTRIBUTE_CONTENT = 92;
	int ELEMENT_CONTENT = 93;
	int XML_COMMENT_END = 94;
	int XML_PI = 95;
	int XML_PI_END = 96;
	int XML_PI_START = 97;
	int CHAR = 98;
	int BASECHAR = 99;
	int IDEOGRAPHIC = 100;
	int COMBINING_CHAR = 101;
	int DIGIT = 102;
	int EXTENDER = 103;
	int LETTER = 104;
	int DIGITS = 105;
	int HEX_DIGITS = 106;
	int NMSTART = 107;
	int NMCHAR = 108;
	int EXPR_COMMENT = 109;
	int PREDEFINED_ENTITY_REF = 110;
	int CHAR_REF = 111;
	int NEXT_TOKEN = 112;
}
