// $ANTLR 2.7.2: "XPathParser2.g" -> "XPathParser2.java"$

	package org.exist.parser;

	import antlr.debug.misc.*;
	import java.io.StringReader;
	import java.io.BufferedReader;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Iterator;
	import java.util.Stack;
	import org.exist.storage.BrokerPool;
	import org.exist.storage.DBBroker;
	import org.exist.storage.analysis.Tokenizer;
	import org.exist.EXistException;
	import org.exist.dom.DocumentSet;
	import org.exist.dom.DocumentImpl;
	import org.exist.dom.QName;
	import org.exist.security.PermissionDeniedException;
	import org.exist.security.User;
	import org.exist.xpath.*;
	import org.exist.xpath.value.*;
	import org.exist.xpath.functions.*;

public interface XPathParser2TokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int QNAME = 4;
	int PREDICATE = 5;
	int FLWOR = 6;
	int PARENTHESIZED = 7;
	int ABSOLUTE_SLASH = 8;
	int ABSOLUTE_DSLASH = 9;
	int WILDCARD = 10;
	int PREFIX_WILDCARD = 11;
	int FUNCTION = 12;
	int UNARY_MINUS = 13;
	int UNARY_PLUS = 14;
	int XPOINTER = 15;
	int XPOINTER_ID = 16;
	int VARIABLE_REF = 17;
	int VARIABLE_BINDING = 18;
	int ELEMENT = 19;
	int ATTRIBUTE = 20;
	int TEXT = 21;
	int VERSION_DECL = 22;
	int NAMESPACE_DECL = 23;
	int DEF_NAMESPACE_DECL = 24;
	int DEF_FUNCTION_NS_DECL = 25;
	int GLOBAL_VAR = 26;
	int FUNCTION_DECL = 27;
	int PROLOG = 28;
	int ATOMIC_TYPE = 29;
	int MODULE = 30;
	int ORDER_BY = 31;
	int POSITIONAL_VAR = 32;
	int LITERAL_xpointer = 33;
	int LPAREN = 34;
	int RPAREN = 35;
	int NCNAME = 36;
	int XQUERY = 37;
	int VERSION = 38;
	int SEMICOLON = 39;
	int LITERAL_declare = 40;
	int LITERAL_namespace = 41;
	int LITERAL_default = 42;
	int LITERAL_function = 43;
	int LITERAL_variable = 44;
	int STRING_LITERAL = 45;
	int EQ = 46;
	int LITERAL_element = 47;
	int DOLLAR = 48;
	int LCURLY = 49;
	int RCURLY = 50;
	int LITERAL_as = 51;
	int COMMA = 52;
	int LITERAL_empty = 53;
	int QUESTION = 54;
	int STAR = 55;
	int PLUS = 56;
	int LITERAL_item = 57;
	int LITERAL_for = 58;
	int LITERAL_let = 59;
	int LITERAL_if = 60;
	int LITERAL_where = 61;
	int LITERAL_return = 62;
	int LITERAL_in = 63;
	int LITERAL_at = 64;
	int COLON = 65;
	int LITERAL_order = 66;
	int LITERAL_by = 67;
	int LITERAL_ascending = 68;
	int LITERAL_descending = 69;
	int LITERAL_greatest = 70;
	int LITERAL_least = 71;
	int LITERAL_then = 72;
	int LITERAL_else = 73;
	int LITERAL_or = 74;
	int LITERAL_and = 75;
	int LITERAL_cast = 76;
	int NEQ = 77;
	int GT = 78;
	int GTEQ = 79;
	int LT = 80;
	int LTEQ = 81;
	int ANDEQ = 82;
	int OREQ = 83;
	int LITERAL_to = 84;
	int MINUS = 85;
	int LITERAL_div = 86;
	int LITERAL_idiv = 87;
	int LITERAL_mod = 88;
	int UNION = 89;
	int SLASH = 90;
	int DSLASH = 91;
	int LITERAL_text = 92;
	int LITERAL_node = 93;
	int SELF = 94;
	int XML_COMMENT = 95;
	int LPPAREN = 96;
	int RPPAREN = 97;
	int AT = 98;
	int PARENT = 99;
	int LITERAL_child = 100;
	int LITERAL_self = 101;
	int LITERAL_attribute = 102;
	int LITERAL_descendant = 103;
	// "descendant-or-self" = 104
	// "following-sibling" = 105
	int LITERAL_parent = 106;
	int LITERAL_ancestor = 107;
	// "ancestor-or-self" = 108
	// "preceding-sibling" = 109
	int DOUBLE_LITERAL = 110;
	int DECIMAL_LITERAL = 111;
	int INTEGER_LITERAL = 112;
	int LITERAL_comment = 113;
	// "processing-instruction" = 114
	// "document-node" = 115
	int WS = 116;
	int END_TAG_START = 117;
	int QUOT = 118;
	int ATTRIBUTE_CONTENT = 119;
	int ELEMENT_CONTENT = 120;
	int XML_COMMENT_END = 121;
	int XML_PI = 122;
	int XML_PI_END = 123;
	int LITERAL_document = 124;
	int LITERAL_collection = 125;
	int XML_PI_START = 126;
	int LETTER = 127;
	int DIGITS = 128;
	int HEX_DIGITS = 129;
	int NMSTART = 130;
	int NMCHAR = 131;
	int EXPR_COMMENT = 132;
	int PREDEFINED_ENTITY_REF = 133;
	int CHAR_REF = 134;
	int NEXT_TOKEN = 135;
	int CHAR = 136;
	int BASECHAR = 137;
	int IDEOGRAPHIC = 138;
	int COMBINING_CHAR = 139;
	int DIGIT = 140;
	int EXTENDER = 141;
}
