// $ANTLR 2.7.4: "XQuery.g" -> "XQueryParser.java"$

	package org.exist.xquery.parser;

	import antlr.debug.misc.*;
	import java.io.StringReader;
	import java.io.BufferedReader;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Iterator;
	import java.util.Stack;
	import org.exist.storage.BrokerPool;
	import org.exist.storage.DBBroker;
	import org.exist.storage.analysis.Tokenizer;
	import org.exist.EXistException;
	import org.exist.dom.DocumentSet;
	import org.exist.dom.DocumentImpl;
	import org.exist.dom.QName;
	import org.exist.security.PermissionDeniedException;
	import org.exist.security.User;
	import org.exist.xquery.*;
	import org.exist.xquery.value.*;
	import org.exist.xquery.functions.*;

public interface XQueryParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int QNAME = 4;
	int PREDICATE = 5;
	int FLWOR = 6;
	int PARENTHESIZED = 7;
	int ABSOLUTE_SLASH = 8;
	int ABSOLUTE_DSLASH = 9;
	int WILDCARD = 10;
	int PREFIX_WILDCARD = 11;
	int FUNCTION = 12;
	int UNARY_MINUS = 13;
	int UNARY_PLUS = 14;
	int XPOINTER = 15;
	int XPOINTER_ID = 16;
	int VARIABLE_REF = 17;
	int VARIABLE_BINDING = 18;
	int ELEMENT = 19;
	int ATTRIBUTE = 20;
	int TEXT = 21;
	int VERSION_DECL = 22;
	int NAMESPACE_DECL = 23;
	int DEF_NAMESPACE_DECL = 24;
	int DEF_COLLATION_DECL = 25;
	int DEF_FUNCTION_NS_DECL = 26;
	int GLOBAL_VAR = 27;
	int FUNCTION_DECL = 28;
	int PROLOG = 29;
	int ATOMIC_TYPE = 30;
	int MODULE = 31;
	int ORDER_BY = 32;
	int POSITIONAL_VAR = 33;
	int BEFORE = 34;
	int AFTER = 35;
	int MODULE_DECL = 36;
	int ATTRIBUTE_TEST = 37;
	int COMP_ELEM_CONSTRUCTOR = 38;
	int COMP_ATTR_CONSTRUCTOR = 39;
	int COMP_TEXT_CONSTRUCTOR = 40;
	int COMP_COMMENT_CONSTRUCTOR = 41;
	int COMP_PI_CONSTRUCTOR = 42;
	int COMP_NS_CONSTRUCTOR = 43;
	int LITERAL_xpointer = 44;
	int LPAREN = 45;
	int RPAREN = 46;
	int NCNAME = 47;
	int LITERAL_module = 48;
	int LITERAL_namespace = 49;
	int EQ = 50;
	int STRING_LITERAL = 51;
	int SEMICOLON = 52;
	int XQUERY = 53;
	int VERSION = 54;
	int LITERAL_declare = 55;
	int LITERAL_default = 56;
	int LITERAL_function = 57;
	int LITERAL_variable = 58;
	int LITERAL_element = 59;
	int LITERAL_collation = 60;
	int DOLLAR = 61;
	int LCURLY = 62;
	int RCURLY = 63;
	int LITERAL_import = 64;
	int LITERAL_at = 65;
	int LITERAL_as = 66;
	int COMMA = 67;
	int LITERAL_empty = 68;
	int QUESTION = 69;
	int STAR = 70;
	int PLUS = 71;
	int LITERAL_item = 72;
	int LITERAL_for = 73;
	int LITERAL_let = 74;
	int LITERAL_some = 75;
	int LITERAL_every = 76;
	int LITERAL_if = 77;
	int LITERAL_where = 78;
	int LITERAL_return = 79;
	int LITERAL_in = 80;
	int COLON = 81;
	int LITERAL_order = 82;
	int LITERAL_by = 83;
	int LITERAL_ascending = 84;
	int LITERAL_descending = 85;
	int LITERAL_greatest = 86;
	int LITERAL_least = 87;
	int LITERAL_satisfies = 88;
	int LITERAL_then = 89;
	int LITERAL_else = 90;
	int LITERAL_or = 91;
	int LITERAL_and = 92;
	int LITERAL_instance = 93;
	int LITERAL_of = 94;
	int LITERAL_cast = 95;
	int LT = 96;
	int GT = 97;
	int LITERAL_eq = 98;
	int LITERAL_ne = 99;
	int LITERAL_lt = 100;
	int LITERAL_le = 101;
	int LITERAL_gt = 102;
	int LITERAL_ge = 103;
	int NEQ = 104;
	int GTEQ = 105;
	int LTEQ = 106;
	int LITERAL_is = 107;
	int LITERAL_isnot = 108;
	int ANDEQ = 109;
	int OREQ = 110;
	int LITERAL_to = 111;
	int MINUS = 112;
	int LITERAL_div = 113;
	int LITERAL_idiv = 114;
	int LITERAL_mod = 115;
	int LITERAL_union = 116;
	int UNION = 117;
	int LITERAL_intersect = 118;
	int LITERAL_except = 119;
	int SLASH = 120;
	int DSLASH = 121;
	int LITERAL_text = 122;
	int LITERAL_node = 123;
	int LITERAL_attribute = 124;
	int LITERAL_comment = 125;
	// "processing-instruction" = 126
	// "document-node" = 127
	int LITERAL_document = 128;
	int SELF = 129;
	int XML_COMMENT = 130;
	int XML_PI = 131;
	int LPPAREN = 132;
	int RPPAREN = 133;
	int AT = 134;
	int PARENT = 135;
	int LITERAL_child = 136;
	int LITERAL_self = 137;
	int LITERAL_descendant = 138;
	// "descendant-or-self" = 139
	// "following-sibling" = 140
	int LITERAL_following = 141;
	int LITERAL_parent = 142;
	int LITERAL_ancestor = 143;
	// "ancestor-or-self" = 144
	// "preceding-sibling" = 145
	int DOUBLE_LITERAL = 146;
	int DECIMAL_LITERAL = 147;
	int INTEGER_LITERAL = 148;
	int END_TAG_START = 149;
	int QUOT = 150;
	int APOS = 151;
	int ATTRIBUTE_CONTENT = 152;
	int ELEMENT_CONTENT = 153;
	int XML_COMMENT_END = 154;
	int XML_PI_END = 155;
	int LITERAL_collection = 156;
	int LITERAL_preceding = 157;
	int COMP_DOC_CONSTRUCTOR = 158;
	int XML_PI_START = 159;
	int LETTER = 160;
	int DIGITS = 161;
	int HEX_DIGITS = 162;
	int NMSTART = 163;
	int NMCHAR = 164;
	int WS = 165;
	int EXPR_COMMENT = 166;
	int PRAGMA = 167;
	int PRAGMA_CONTENT = 168;
	int PRAGMA_QNAME = 169;
	int PREDEFINED_ENTITY_REF = 170;
	int CHAR_REF = 171;
	int NEXT_TOKEN = 172;
	int CHAR = 173;
	int BASECHAR = 174;
	int IDEOGRAPHIC = 175;
	int COMBINING_CHAR = 176;
	int DIGIT = 177;
	int EXTENDER = 178;
}
