// $ANTLR 2.7.4: "XQuery.g" -> "XQueryParser.java"$

	package org.exist.xquery.parser;

	import antlr.debug.misc.*;
	import java.io.StringReader;
	import java.io.BufferedReader;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Iterator;
	import java.util.Stack;
	import org.exist.storage.BrokerPool;
	import org.exist.storage.DBBroker;
	import org.exist.storage.analysis.Tokenizer;
	import org.exist.EXistException;
	import org.exist.dom.DocumentSet;
	import org.exist.dom.DocumentImpl;
	import org.exist.dom.QName;
	import org.exist.security.PermissionDeniedException;
	import org.exist.security.User;
	import org.exist.xquery.*;
	import org.exist.xquery.value.*;
	import org.exist.xquery.functions.*;

public interface XQueryTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int QNAME = 4;
	int PREDICATE = 5;
	int FLWOR = 6;
	int PARENTHESIZED = 7;
	int ABSOLUTE_SLASH = 8;
	int ABSOLUTE_DSLASH = 9;
	int WILDCARD = 10;
	int PREFIX_WILDCARD = 11;
	int FUNCTION = 12;
	int UNARY_MINUS = 13;
	int UNARY_PLUS = 14;
	int XPOINTER = 15;
	int XPOINTER_ID = 16;
	int VARIABLE_REF = 17;
	int VARIABLE_BINDING = 18;
	int ELEMENT = 19;
	int ATTRIBUTE = 20;
	int ATTRIBUTE_CONTENT = 21;
	int TEXT = 22;
	int VERSION_DECL = 23;
	int NAMESPACE_DECL = 24;
	int DEF_NAMESPACE_DECL = 25;
	int DEF_COLLATION_DECL = 26;
	int DEF_FUNCTION_NS_DECL = 27;
	int GLOBAL_VAR = 28;
	int FUNCTION_DECL = 29;
	int PROLOG = 30;
	int OPTION = 31;
	int ATOMIC_TYPE = 32;
	int MODULE = 33;
	int ORDER_BY = 34;
	int POSITIONAL_VAR = 35;
	int BEFORE = 36;
	int AFTER = 37;
	int MODULE_DECL = 38;
	int MODULE_IMPORT = 39;
	int SCHEMA_IMPORT = 40;
	int ATTRIBUTE_TEST = 41;
	int COMP_ELEM_CONSTRUCTOR = 42;
	int COMP_ATTR_CONSTRUCTOR = 43;
	int COMP_TEXT_CONSTRUCTOR = 44;
	int COMP_COMMENT_CONSTRUCTOR = 45;
	int COMP_PI_CONSTRUCTOR = 46;
	int COMP_NS_CONSTRUCTOR = 47;
	int COMP_DOC_CONSTRUCTOR = 48;
	int LITERAL_xpointer = 49;
	int LPAREN = 50;
	int RPAREN = 51;
	int NCNAME = 52;
	int LITERAL_xquery = 53;
	int LITERAL_version = 54;
	int SEMICOLON = 55;
	int LITERAL_module = 56;
	int LITERAL_namespace = 57;
	int EQ = 58;
	int STRING_LITERAL = 59;
	int LITERAL_declare = 60;
	int LITERAL_default = 61;
	int LITERAL_xmlspace = 62;
	int LITERAL_ordering = 63;
	int LITERAL_construction = 64;
	// "base-uri" = 65
	int LITERAL_option = 66;
	int LITERAL_function = 67;
	int LITERAL_variable = 68;
	int LITERAL_import = 69;
	int LITERAL_encoding = 70;
	int LITERAL_collation = 71;
	int LITERAL_element = 72;
	int LITERAL_preserve = 73;
	int LITERAL_strip = 74;
	int LITERAL_ordered = 75;
	int LITERAL_unordered = 76;
	int DOLLAR = 77;
	int LCURLY = 78;
	int RCURLY = 79;
	int COLON = 80;
	int LITERAL_external = 81;
	int LITERAL_at = 82;
	int LITERAL_schema = 83;
	int LITERAL_as = 84;
	int COMMA = 85;
	int LITERAL_empty = 86;
	int QUESTION = 87;
	int STAR = 88;
	int PLUS = 89;
	int LITERAL_item = 90;
	int LITERAL_for = 91;
	int LITERAL_let = 92;
	int LITERAL_some = 93;
	int LITERAL_every = 94;
	int LITERAL_if = 95;
	int LITERAL_update = 96;
	int LITERAL_replace = 97;
	int LITERAL_value = 98;
	int LITERAL_insert = 99;
	int LITERAL_delete = 100;
	int LITERAL_rename = 101;
	int LITERAL_with = 102;
	int LITERAL_into = 103;
	int LITERAL_preceding = 104;
	int LITERAL_following = 105;
	int LITERAL_where = 106;
	int LITERAL_return = 107;
	int LITERAL_in = 108;
	int LITERAL_order = 109;
	int LITERAL_by = 110;
	int LITERAL_ascending = 111;
	int LITERAL_descending = 112;
	int LITERAL_greatest = 113;
	int LITERAL_least = 114;
	int LITERAL_satisfies = 115;
	int LITERAL_typeswitch = 116;
	int LITERAL_case = 117;
	int LITERAL_then = 118;
	int LITERAL_else = 119;
	int LITERAL_or = 120;
	int LITERAL_and = 121;
	int LITERAL_instance = 122;
	int LITERAL_of = 123;
	int LITERAL_castable = 124;
	int LITERAL_cast = 125;
	int LT = 126;
	int GT = 127;
	int LITERAL_eq = 128;
	int LITERAL_ne = 129;
	int LITERAL_lt = 130;
	int LITERAL_le = 131;
	int LITERAL_gt = 132;
	int LITERAL_ge = 133;
	int NEQ = 134;
	int GTEQ = 135;
	int LTEQ = 136;
	int LITERAL_is = 137;
	int LITERAL_isnot = 138;
	int ANDEQ = 139;
	int OREQ = 140;
	int LITERAL_to = 141;
	int MINUS = 142;
	int LITERAL_div = 143;
	int LITERAL_idiv = 144;
	int LITERAL_mod = 145;
	int LITERAL_union = 146;
	int UNION = 147;
	int LITERAL_intersect = 148;
	int LITERAL_except = 149;
	int SLASH = 150;
	int DSLASH = 151;
	int LITERAL_text = 152;
	int LITERAL_node = 153;
	int LITERAL_attribute = 154;
	int LITERAL_comment = 155;
	// "processing-instruction" = 156
	// "document-node" = 157
	int LITERAL_document = 158;
	int SELF = 159;
	int XML_COMMENT = 160;
	int XML_PI = 161;
	int LPPAREN = 162;
	int RPPAREN = 163;
	int AT = 164;
	int PARENT = 165;
	int LITERAL_child = 166;
	int LITERAL_self = 167;
	int LITERAL_descendant = 168;
	// "descendant-or-self" = 169
	// "following-sibling" = 170
	int LITERAL_parent = 171;
	int LITERAL_ancestor = 172;
	// "ancestor-or-self" = 173
	// "preceding-sibling" = 174
	int DOUBLE_LITERAL = 175;
	int DECIMAL_LITERAL = 176;
	int INTEGER_LITERAL = 177;
	int END_TAG_START = 178;
	int QUOT = 179;
	int APOS = 180;
	int QUOT_ATTRIBUTE_CONTENT = 181;
	int APOS_ATTRIBUTE_CONTENT = 182;
	int ELEMENT_CONTENT = 183;
	int XML_COMMENT_END = 184;
	int XML_PI_END = 185;
	int XML_CDATA = 186;
	int LITERAL_collection = 187;
	int LITERAL_validate = 188;
	int XML_PI_START = 189;
	int XML_CDATA_START = 190;
	int XML_CDATA_END = 191;
	int LETTER = 192;
	int DIGITS = 193;
	int HEX_DIGITS = 194;
	int NMSTART = 195;
	int NMCHAR = 196;
	int WS = 197;
	int EXPR_COMMENT = 198;
	int PRAGMA = 199;
	int PRAGMA_CONTENT = 200;
	int PRAGMA_QNAME = 201;
	int PREDEFINED_ENTITY_REF = 202;
	int CHAR_REF = 203;
	int NEXT_TOKEN = 204;
	int CHAR = 205;
	int BASECHAR = 206;
	int IDEOGRAPHIC = 207;
	int COMBINING_CHAR = 208;
	int DIGIT = 209;
	int EXTENDER = 210;
}
