// $ANTLR 2.7.4: "XQuery.g" -> "XQueryParser.java"$

	package org.exist.xquery.parser;

	import antlr.debug.misc.*;
	import java.io.StringReader;
	import java.io.BufferedReader;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Iterator;
	import java.util.Stack;
	import org.exist.storage.BrokerPool;
	import org.exist.storage.DBBroker;
	import org.exist.storage.analysis.Tokenizer;
	import org.exist.EXistException;
	import org.exist.dom.DocumentSet;
	import org.exist.dom.DocumentImpl;
	import org.exist.dom.QName;
	import org.exist.security.PermissionDeniedException;
	import org.exist.security.User;
	import org.exist.xquery.*;
	import org.exist.xquery.value.*;
	import org.exist.xquery.functions.*;

public interface XQueryParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int QNAME = 4;
	int PREDICATE = 5;
	int FLWOR = 6;
	int PARENTHESIZED = 7;
	int ABSOLUTE_SLASH = 8;
	int ABSOLUTE_DSLASH = 9;
	int WILDCARD = 10;
	int PREFIX_WILDCARD = 11;
	int FUNCTION = 12;
	int UNARY_MINUS = 13;
	int UNARY_PLUS = 14;
	int XPOINTER = 15;
	int XPOINTER_ID = 16;
	int VARIABLE_REF = 17;
	int VARIABLE_BINDING = 18;
	int ELEMENT = 19;
	int ATTRIBUTE = 20;
	int TEXT = 21;
	int VERSION_DECL = 22;
	int NAMESPACE_DECL = 23;
	int DEF_NAMESPACE_DECL = 24;
	int DEF_FUNCTION_NS_DECL = 25;
	int GLOBAL_VAR = 26;
	int FUNCTION_DECL = 27;
	int PROLOG = 28;
	int ATOMIC_TYPE = 29;
	int MODULE = 30;
	int ORDER_BY = 31;
	int POSITIONAL_VAR = 32;
	int BEFORE = 33;
	int AFTER = 34;
	int MODULE_DECL = 35;
	int ATTRIBUTE_TEST = 36;
	int LITERAL_xpointer = 37;
	int LPAREN = 38;
	int RPAREN = 39;
	int NCNAME = 40;
	int LITERAL_module = 41;
	int LITERAL_namespace = 42;
	int EQ = 43;
	int STRING_LITERAL = 44;
	int SEMICOLON = 45;
	int XQUERY = 46;
	int VERSION = 47;
	int LITERAL_declare = 48;
	int LITERAL_default = 49;
	int LITERAL_function = 50;
	int LITERAL_variable = 51;
	int LITERAL_element = 52;
	int DOLLAR = 53;
	int LCURLY = 54;
	int RCURLY = 55;
	int LITERAL_import = 56;
	int LITERAL_at = 57;
	int LITERAL_as = 58;
	int COMMA = 59;
	int LITERAL_empty = 60;
	int QUESTION = 61;
	int STAR = 62;
	int PLUS = 63;
	int LITERAL_item = 64;
	int LITERAL_for = 65;
	int LITERAL_let = 66;
	int LITERAL_some = 67;
	int LITERAL_every = 68;
	int LITERAL_if = 69;
	int LITERAL_where = 70;
	int LITERAL_return = 71;
	int LITERAL_in = 72;
	int COLON = 73;
	int LITERAL_order = 74;
	int LITERAL_by = 75;
	int LITERAL_ascending = 76;
	int LITERAL_descending = 77;
	int LITERAL_greatest = 78;
	int LITERAL_least = 79;
	int LITERAL_satisfies = 80;
	int LITERAL_then = 81;
	int LITERAL_else = 82;
	int LITERAL_or = 83;
	int LITERAL_and = 84;
	int LITERAL_instance = 85;
	int LITERAL_of = 86;
	int LITERAL_cast = 87;
	int LT = 88;
	int GT = 89;
	int LITERAL_eq = 90;
	int LITERAL_ne = 91;
	int LITERAL_lt = 92;
	int LITERAL_le = 93;
	int LITERAL_gt = 94;
	int LITERAL_ge = 95;
	int NEQ = 96;
	int GTEQ = 97;
	int LTEQ = 98;
	int LITERAL_is = 99;
	int LITERAL_isnot = 100;
	int ANDEQ = 101;
	int OREQ = 102;
	int LITERAL_to = 103;
	int MINUS = 104;
	int LITERAL_div = 105;
	int LITERAL_idiv = 106;
	int LITERAL_mod = 107;
	int LITERAL_union = 108;
	int UNION = 109;
	int LITERAL_intersect = 110;
	int LITERAL_except = 111;
	int SLASH = 112;
	int DSLASH = 113;
	int LITERAL_text = 114;
	int LITERAL_node = 115;
	int LITERAL_attribute = 116;
	int LITERAL_comment = 117;
	// "processing-instruction" = 118
	// "document-node" = 119
	int SELF = 120;
	int XML_COMMENT = 121;
	int XML_PI = 122;
	int LPPAREN = 123;
	int RPPAREN = 124;
	int AT = 125;
	int PARENT = 126;
	int LITERAL_child = 127;
	int LITERAL_self = 128;
	int LITERAL_descendant = 129;
	// "descendant-or-self" = 130
	// "following-sibling" = 131
	int LITERAL_following = 132;
	int LITERAL_parent = 133;
	int LITERAL_ancestor = 134;
	// "ancestor-or-self" = 135
	// "preceding-sibling" = 136
	int DOUBLE_LITERAL = 137;
	int DECIMAL_LITERAL = 138;
	int INTEGER_LITERAL = 139;
	int END_TAG_START = 140;
	int QUOT = 141;
	int ATTRIBUTE_CONTENT = 142;
	int ELEMENT_CONTENT = 143;
	int XML_COMMENT_END = 144;
	int XML_PI_END = 145;
	int LITERAL_document = 146;
	int LITERAL_collection = 147;
	int LITERAL_preceding = 148;
	int XML_PI_START = 149;
	int LETTER = 150;
	int DIGITS = 151;
	int HEX_DIGITS = 152;
	int NMSTART = 153;
	int NMCHAR = 154;
	int WS = 155;
	int EXPR_COMMENT = 156;
	int PREDEFINED_ENTITY_REF = 157;
	int CHAR_REF = 158;
	int NEXT_TOKEN = 159;
	int CHAR = 160;
	int BASECHAR = 161;
	int IDEOGRAPHIC = 162;
	int COMBINING_CHAR = 163;
	int DIGIT = 164;
	int EXTENDER = 165;
}
