// $ANTLR 2.7.4: "XQueryTree.g" -> "XQueryTreeParser.java"$

	package org.exist.xquery.parser;

	import antlr.debug.misc.*;
	import java.io.StringReader;
	import java.io.BufferedReader;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Iterator;
	import java.util.Stack;
	import org.exist.storage.BrokerPool;
	import org.exist.storage.DBBroker;
	import org.exist.storage.analysis.Tokenizer;
	import org.exist.EXistException;
	import org.exist.dom.DocumentSet;
	import org.exist.dom.DocumentImpl;
	import org.exist.dom.QName;
	import org.exist.security.PermissionDeniedException;
	import org.exist.security.User;
	import org.exist.xquery.*;
	import org.exist.xquery.value.*;
	import org.exist.xquery.functions.*;

public interface XQueryTreeParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int QNAME = 4;
	int PREDICATE = 5;
	int FLWOR = 6;
	int PARENTHESIZED = 7;
	int ABSOLUTE_SLASH = 8;
	int ABSOLUTE_DSLASH = 9;
	int WILDCARD = 10;
	int PREFIX_WILDCARD = 11;
	int FUNCTION = 12;
	int UNARY_MINUS = 13;
	int UNARY_PLUS = 14;
	int XPOINTER = 15;
	int XPOINTER_ID = 16;
	int VARIABLE_REF = 17;
	int VARIABLE_BINDING = 18;
	int ELEMENT = 19;
	int ATTRIBUTE = 20;
	int TEXT = 21;
	int VERSION_DECL = 22;
	int NAMESPACE_DECL = 23;
	int DEF_NAMESPACE_DECL = 24;
	int DEF_COLLATION_DECL = 25;
	int DEF_FUNCTION_NS_DECL = 26;
	int GLOBAL_VAR = 27;
	int FUNCTION_DECL = 28;
	int PROLOG = 29;
	int ATOMIC_TYPE = 30;
	int MODULE = 31;
	int ORDER_BY = 32;
	int POSITIONAL_VAR = 33;
	int BEFORE = 34;
	int AFTER = 35;
	int MODULE_DECL = 36;
	int ATTRIBUTE_TEST = 37;
	int COMP_ELEM_CONSTRUCTOR = 38;
	int COMP_ATTR_CONSTRUCTOR = 39;
	int COMP_TEXT_CONSTRUCTOR = 40;
	int COMP_COMMENT_CONSTRUCTOR = 41;
	int COMP_PI_CONSTRUCTOR = 42;
	int COMP_NS_CONSTRUCTOR = 43;
	int COMP_DOC_CONSTRUCTOR = 44;
	int LITERAL_xpointer = 45;
	int LPAREN = 46;
	int RPAREN = 47;
	int NCNAME = 48;
	int LITERAL_xquery = 49;
	int LITERAL_version = 50;
	int SEMICOLON = 51;
	int LITERAL_module = 52;
	int LITERAL_namespace = 53;
	int EQ = 54;
	int STRING_LITERAL = 55;
	int LITERAL_import = 56;
	int LITERAL_declare = 57;
	int LITERAL_default = 58;
	int LITERAL_xmlspace = 59;
	int LITERAL_function = 60;
	int LITERAL_variable = 61;
	int LITERAL_collation = 62;
	int LITERAL_element = 63;
	int LITERAL_preserve = 64;
	int LITERAL_strip = 65;
	int DOLLAR = 66;
	int LCURLY = 67;
	int RCURLY = 68;
	int LITERAL_at = 69;
	int LITERAL_as = 70;
	int COMMA = 71;
	int LITERAL_empty = 72;
	int QUESTION = 73;
	int STAR = 74;
	int PLUS = 75;
	int LITERAL_item = 76;
	int LITERAL_for = 77;
	int LITERAL_let = 78;
	int LITERAL_some = 79;
	int LITERAL_every = 80;
	int LITERAL_if = 81;
	int LITERAL_where = 82;
	int LITERAL_return = 83;
	int LITERAL_in = 84;
	int COLON = 85;
	int LITERAL_order = 86;
	int LITERAL_by = 87;
	int LITERAL_ascending = 88;
	int LITERAL_descending = 89;
	int LITERAL_greatest = 90;
	int LITERAL_least = 91;
	int LITERAL_satisfies = 92;
	int LITERAL_then = 93;
	int LITERAL_else = 94;
	int LITERAL_or = 95;
	int LITERAL_and = 96;
	int LITERAL_instance = 97;
	int LITERAL_of = 98;
	int LITERAL_castable = 99;
	int LITERAL_cast = 100;
	int LT = 101;
	int GT = 102;
	int LITERAL_eq = 103;
	int LITERAL_ne = 104;
	int LITERAL_lt = 105;
	int LITERAL_le = 106;
	int LITERAL_gt = 107;
	int LITERAL_ge = 108;
	int NEQ = 109;
	int GTEQ = 110;
	int LTEQ = 111;
	int LITERAL_is = 112;
	int LITERAL_isnot = 113;
	int ANDEQ = 114;
	int OREQ = 115;
	int LITERAL_to = 116;
	int MINUS = 117;
	int LITERAL_div = 118;
	int LITERAL_idiv = 119;
	int LITERAL_mod = 120;
	int LITERAL_union = 121;
	int UNION = 122;
	int LITERAL_intersect = 123;
	int LITERAL_except = 124;
	int SLASH = 125;
	int DSLASH = 126;
	int LITERAL_text = 127;
	int LITERAL_node = 128;
	int LITERAL_attribute = 129;
	int LITERAL_comment = 130;
	// "processing-instruction" = 131
	// "document-node" = 132
	int LITERAL_document = 133;
	int SELF = 134;
	int XML_COMMENT = 135;
	int XML_PI = 136;
	int LPPAREN = 137;
	int RPPAREN = 138;
	int AT = 139;
	int PARENT = 140;
	int LITERAL_child = 141;
	int LITERAL_self = 142;
	int LITERAL_descendant = 143;
	// "descendant-or-self" = 144
	// "following-sibling" = 145
	int LITERAL_following = 146;
	int LITERAL_parent = 147;
	int LITERAL_ancestor = 148;
	// "ancestor-or-self" = 149
	// "preceding-sibling" = 150
	int DOUBLE_LITERAL = 151;
	int DECIMAL_LITERAL = 152;
	int INTEGER_LITERAL = 153;
	int END_TAG_START = 154;
	int QUOT = 155;
	int APOS = 156;
	int ATTRIBUTE_CONTENT = 157;
	int ELEMENT_CONTENT = 158;
	int XML_COMMENT_END = 159;
	int XML_PI_END = 160;
	int XML_CDATA = 161;
	int XML_CDATA_END = 162;
	int LITERAL_collection = 163;
	int LITERAL_preceding = 164;
	int XML_PI_START = 165;
	int XML_CDATA_START = 166;
	int LETTER = 167;
	int DIGITS = 168;
	int HEX_DIGITS = 169;
	int NMSTART = 170;
	int NMCHAR = 171;
	int WS = 172;
	int EXPR_COMMENT = 173;
	int PRAGMA = 174;
	int PRAGMA_CONTENT = 175;
	int PRAGMA_QNAME = 176;
	int PREDEFINED_ENTITY_REF = 177;
	int CHAR_REF = 178;
	int NEXT_TOKEN = 179;
	int CHAR = 180;
	int BASECHAR = 181;
	int IDEOGRAPHIC = 182;
	int COMBINING_CHAR = 183;
	int DIGIT = 184;
	int EXTENDER = 185;
}
