// $ANTLR 2.7.4: "XQuery.g" -> "XQueryParser.java"$

	package org.exist.xquery.parser;

	import antlr.debug.misc.*;
	import java.io.StringReader;
	import java.io.BufferedReader;
	import java.io.InputStreamReader;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Iterator;
	import java.util.Stack;
	import org.exist.storage.BrokerPool;
	import org.exist.storage.DBBroker;
	import org.exist.storage.analysis.Tokenizer;
	import org.exist.EXistException;
	import org.exist.dom.DocumentSet;
	import org.exist.dom.DocumentImpl;
	import org.exist.dom.QName;
	import org.exist.security.PermissionDeniedException;
	import org.exist.security.User;
	import org.exist.xquery.*;
	import org.exist.xquery.value.*;
	import org.exist.xquery.functions.*;

public interface XQueryParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int QNAME = 4;
	int PREDICATE = 5;
	int FLWOR = 6;
	int PARENTHESIZED = 7;
	int ABSOLUTE_SLASH = 8;
	int ABSOLUTE_DSLASH = 9;
	int WILDCARD = 10;
	int PREFIX_WILDCARD = 11;
	int FUNCTION = 12;
	int UNARY_MINUS = 13;
	int UNARY_PLUS = 14;
	int XPOINTER = 15;
	int XPOINTER_ID = 16;
	int VARIABLE_REF = 17;
	int VARIABLE_BINDING = 18;
	int ELEMENT = 19;
	int ATTRIBUTE = 20;
	int TEXT = 21;
	int VERSION_DECL = 22;
	int NAMESPACE_DECL = 23;
	int DEF_NAMESPACE_DECL = 24;
	int DEF_FUNCTION_NS_DECL = 25;
	int GLOBAL_VAR = 26;
	int FUNCTION_DECL = 27;
	int PROLOG = 28;
	int ATOMIC_TYPE = 29;
	int MODULE = 30;
	int ORDER_BY = 31;
	int POSITIONAL_VAR = 32;
	int BEFORE = 33;
	int AFTER = 34;
	int MODULE_DECL = 35;
	int ATTRIBUTE_TEST = 36;
	int COMP_ELEM_CONSTRUCTOR = 37;
	int COMP_ATTR_CONSTRUCTOR = 38;
	int COMP_TEXT_CONSTRUCTOR = 39;
	int COMP_COMMENT_CONSTRUCTOR = 40;
	int COMP_PI_CONSTRUCTOR = 41;
	int LITERAL_xpointer = 42;
	int LPAREN = 43;
	int RPAREN = 44;
	int NCNAME = 45;
	int LITERAL_module = 46;
	int LITERAL_namespace = 47;
	int EQ = 48;
	int STRING_LITERAL = 49;
	int SEMICOLON = 50;
	int XQUERY = 51;
	int VERSION = 52;
	int LITERAL_declare = 53;
	int LITERAL_default = 54;
	int LITERAL_function = 55;
	int LITERAL_variable = 56;
	int LITERAL_element = 57;
	int DOLLAR = 58;
	int LCURLY = 59;
	int RCURLY = 60;
	int LITERAL_import = 61;
	int LITERAL_at = 62;
	int LITERAL_as = 63;
	int COMMA = 64;
	int LITERAL_empty = 65;
	int QUESTION = 66;
	int STAR = 67;
	int PLUS = 68;
	int LITERAL_item = 69;
	int LITERAL_for = 70;
	int LITERAL_let = 71;
	int LITERAL_some = 72;
	int LITERAL_every = 73;
	int LITERAL_if = 74;
	int LITERAL_where = 75;
	int LITERAL_return = 76;
	int LITERAL_in = 77;
	int COLON = 78;
	int LITERAL_order = 79;
	int LITERAL_by = 80;
	int LITERAL_ascending = 81;
	int LITERAL_descending = 82;
	int LITERAL_greatest = 83;
	int LITERAL_least = 84;
	int LITERAL_satisfies = 85;
	int LITERAL_then = 86;
	int LITERAL_else = 87;
	int LITERAL_or = 88;
	int LITERAL_and = 89;
	int LITERAL_instance = 90;
	int LITERAL_of = 91;
	int LITERAL_cast = 92;
	int LT = 93;
	int GT = 94;
	int LITERAL_eq = 95;
	int LITERAL_ne = 96;
	int LITERAL_lt = 97;
	int LITERAL_le = 98;
	int LITERAL_gt = 99;
	int LITERAL_ge = 100;
	int NEQ = 101;
	int GTEQ = 102;
	int LTEQ = 103;
	int LITERAL_is = 104;
	int LITERAL_isnot = 105;
	int ANDEQ = 106;
	int OREQ = 107;
	int LITERAL_to = 108;
	int MINUS = 109;
	int LITERAL_div = 110;
	int LITERAL_idiv = 111;
	int LITERAL_mod = 112;
	int LITERAL_union = 113;
	int UNION = 114;
	int LITERAL_intersect = 115;
	int LITERAL_except = 116;
	int SLASH = 117;
	int DSLASH = 118;
	int LITERAL_text = 119;
	int LITERAL_node = 120;
	int LITERAL_attribute = 121;
	int LITERAL_comment = 122;
	// "processing-instruction" = 123
	// "document-node" = 124
	int LITERAL_document = 125;
	int SELF = 126;
	int XML_COMMENT = 127;
	int XML_PI = 128;
	int LPPAREN = 129;
	int RPPAREN = 130;
	int AT = 131;
	int PARENT = 132;
	int LITERAL_child = 133;
	int LITERAL_self = 134;
	int LITERAL_descendant = 135;
	// "descendant-or-self" = 136
	// "following-sibling" = 137
	int LITERAL_following = 138;
	int LITERAL_parent = 139;
	int LITERAL_ancestor = 140;
	// "ancestor-or-self" = 141
	// "preceding-sibling" = 142
	int DOUBLE_LITERAL = 143;
	int DECIMAL_LITERAL = 144;
	int INTEGER_LITERAL = 145;
	int END_TAG_START = 146;
	int QUOT = 147;
	int ATTRIBUTE_CONTENT = 148;
	int ELEMENT_CONTENT = 149;
	int XML_COMMENT_END = 150;
	int XML_PI_END = 151;
	int LITERAL_collection = 152;
	int LITERAL_preceding = 153;
	int COMP_DOC_CONSTRUCTOR = 154;
	int XML_PI_START = 155;
	int LETTER = 156;
	int DIGITS = 157;
	int HEX_DIGITS = 158;
	int NMSTART = 159;
	int NMCHAR = 160;
	int WS = 161;
	int EXPR_COMMENT = 162;
	int PREDEFINED_ENTITY_REF = 163;
	int CHAR_REF = 164;
	int NEXT_TOKEN = 165;
	int CHAR = 166;
	int BASECHAR = 167;
	int IDEOGRAPHIC = 168;
	int COMBINING_CHAR = 169;
	int DIGIT = 170;
	int EXTENDER = 171;
}
