name: Javadoc
on: [push, pull_request]
permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.jdk }} Javadocs 
    strategy:
      matrix: 
        jdk: ['17']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Javadoc
        run: mvn -V -B -q -T 2C javadoc:javadoc
      - name: Archive logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-jdk${{ matrix.jdk }}-javadoc-logs
          retention-days: 5
          path: |
            **/target/site/apidocs/javadoc.sh
            **/target/site/apidocs/options
            **/target/site/apidocs/packages
      - name: Delete local cache
        if: ${{ failure() }}
        run: rm -rf ~/.m2/repository
      - name: Store empty cache
        if: ${{ failure() }}
        uses: actions/cache/save@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
