name: Flush cache
on: workflow_dispatch

permissions:
  contents: read

jobs:
  clean_cache:
    name: Clean cache
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Delete local cache
        run: rm -rf ~/.m2/repository
