name: Publish Snaphots to Github Packages

on:
  push:
    branches:
      - develop
  workflow_dispatch: # Allow manual triggering

jobs:
  publish-snapshots:
    name: Deploy Snapshots
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
      - uses: ./.github/actions/maven-cache
      - uses: ./.github/actions/maven-github-settings
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy SNAPSHOT maven artefacts
        timeout-minutes: 40
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw -V -B --no-transfer-progress -q -DskipTests -Ddependency-check.skip=true \
          -P !mac-dmg-on-unix,!installer,!concurrency-stress-tests,!micro-benchmarks,skip-build-dist-archives \
          clean deploy
