name: CI
on: [push, pull_request]
jobs:
  build:
    name: (${{ matrix.os }} / JDK ${{ matrix.jdk }}) Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jdk: ['8', '11']
        include:
          - os: ubuntu-latest
            jdk: 15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
# NOTE(AR) The `-T 2C` enables multi-threaded builds below, faster, but may need to be disabled when diagnosing problems 
      - name: Maven Build
        run: mvn -V -B -q -T 2C -DskipTests=true "-Dmaven.javadoc.skip=true" install
      - name: Maven Test
        run: mvn -V -B "-Dsurefire.useFile=false" -DtrimStackTrace=false test
      - name: Maven License Check
        run: mvn -V -B license:check
# TODO(AR) test and license:check should be replaced by verify, but seems to cause an error on GitHub Actions
#      - name: Maven Verify
#        run: mvn -V -B verify
      - name: Maven Javadoc
        run: mvn -V -B -q -T 2C javadoc:javadoc
  deploy:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.base_ref ==  'develop' || github.base_ref ==  'master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Make buildkit default
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build images
        run: mvn -V -B -q -Pdocker -DskipTests -Ddependency-check.skip=true clean package
      - name: Check local images
        run: docker image ls
      - name: Build and push latest images
        if: github.ref == 'refs/heads/develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: mvn -q -Ddocker.tag=latest -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:build docker:push
        working-directory: ./exist-docker
      - name: Build and push release images
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: mvn -q -Ddocker.tag=release -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:build docker:push
        working-directory: ./exist-docker
